/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -i dbusabstractinterface.h -c Mpris2TrackListProxy -p tracklist_proxy TrackList_Node.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "tracklist_proxy.h"

/*
 * Implementation of interface class Mpris2TrackListProxy
 */

Mpris2TrackListProxy::Mpris2TrackListProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : DBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

Mpris2TrackListProxy::~Mpris2TrackListProxy()
{
}

