/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -p mpristracklist -N -c MprisTracklist org.freedesktop.MediaPlayer.tracklist.xml
 *
 * qdbusxml2cpp is Copyright (C) 2009 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef MPRISTRACKLIST_H_1240260010
#define MPRISTRACKLIST_H_1240260010

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>

/*
 * Proxy class for interface org.freedesktop.MediaPlayer
 */
class MprisTracklist: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.MediaPlayer"; }

public:
    MprisTracklist(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~MprisTracklist();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<int> AddTrack(const QString &in0, bool in1)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0) << qVariantFromValue(in1);
        return asyncCallWithArgumentList(QLatin1String("AddTrack"), argumentList);
    }

    inline QDBusPendingReply<> DelTrack(int in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("DelTrack"), argumentList);
    }

    inline QDBusPendingReply<int> GetCurrentTrack()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetCurrentTrack"), argumentList);
    }

    inline QDBusPendingReply<int> GetLength()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetLength"), argumentList);
    }

    inline QDBusPendingReply<QVariantMap> GetMetadata(int in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("GetMetadata"), argumentList);
    }

    inline QDBusPendingReply<> SetLoop(bool in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("SetLoop"), argumentList);
    }

    inline QDBusPendingReply<> SetRandom(bool in0)
    {
        QList<QVariant> argumentList;
        argumentList << qVariantFromValue(in0);
        return asyncCallWithArgumentList(QLatin1String("SetRandom"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void TrackListChange(int in0);
};

#endif
