/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -p mprisroot -N -c MprisRoot -i dbustypes.h org.freedesktop.MediaPlayer.root.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef MPRISROOT_H_1218542620
#define MPRISROOT_H_1218542620

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "dbustypes.h"

/*
 * Proxy class for interface org.freedesktop.MediaPlayer
 */
class MprisRoot: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.MediaPlayer"; }

public:
    MprisRoot(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~MprisRoot();

public Q_SLOTS: // METHODS
    inline QDBusReply<QString> Identity()
    {
        QList<QVariant> argumentList;
        return callWithArgumentList(QDBus::Block, QLatin1String("Identity"), argumentList);
    }

    inline QDBusReply<DBusVersion> MprisVersion()
    {
        QList<QVariant> argumentList;
        return callWithArgumentList(QDBus::Block, QLatin1String("MprisVersion"), argumentList);
    }

    inline QDBusReply<void> Quit()
    {
        QList<QVariant> argumentList;
        return callWithArgumentList(QDBus::Block, QLatin1String("Quit"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
