/*
 * This file was generated by dbusxml2cpp version 0.6
 * Command line was: dbusxml2cpp -p mprisplayer -N -c MprisPlayer -i dbustypes.h org.freedesktop.MediaPlayer.player.xml
 *
 * dbusxml2cpp is Copyright (C) 2006 Trolltech ASA. All rights reserved.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "mprisplayer.h"

/*
 * Implementation of interface class MprisPlayer
 */

MprisPlayer::MprisPlayer(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

MprisPlayer::~MprisPlayer()
{
}

