/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -i mpristypes.h -c Mpris1PlayerProxy -p player_proxy org.freedesktop.MediaPlayer.player.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "player_proxy.h"

/*
 * Implementation of interface class Mpris1PlayerProxy
 */

Mpris1PlayerProxy::Mpris1PlayerProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

Mpris1PlayerProxy::~Mpris1PlayerProxy()
{
}

