/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -i mpristypes.h -c Mpris1RootProxy -p root_proxy org.freedesktop.MediaPlayer.root.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#include "root_proxy.h"

/*
 * Implementation of interface class Mpris1RootProxy
 */

Mpris1RootProxy::Mpris1RootProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent)
    : QDBusAbstractInterface(service, path, staticInterfaceName(), connection, parent)
{
}

Mpris1RootProxy::~Mpris1RootProxy()
{
}

