/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -N -i mpristypes.h -c Mpris1RootProxy -p root_proxy org.freedesktop.MediaPlayer.root.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef ROOT_PROXY_H_1281721680
#define ROOT_PROXY_H_1281721680

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "mpristypes.h"

/*
 * Proxy class for interface org.freedesktop.MediaPlayer
 */
class Mpris1RootProxy: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.freedesktop.MediaPlayer"; }

public:
    Mpris1RootProxy(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~Mpris1RootProxy();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<QString> Identity()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Identity"), argumentList);
    }

    inline QDBusPendingReply<Mpris::Version> MprisVersion()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("MprisVersion"), argumentList);
    }

    inline QDBusPendingReply<> Quit()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("Quit"), argumentList);
    }

Q_SIGNALS: // SIGNALS
};

#endif
